### ISSUE TITLE
How to calculate the GPU memory used in Fig1 (C)?

### ISSUE THREAD

**Issue by GaryGuTC** [OpenGVLab/Vision-RWKV#15]
Hi 

Thanks so much for your excellent work.
I have some questions about calculating the GPU memory used by inputting different-resolution images (Fig1 C). 

Thanks so much for your help
Best regards

**Comment by duanduanduanyuchen** [comment]
Hi! I apply the API of pytorch `torch.cuda.max_memory_allocated()`.
