### ISSUE TITLE
Will the pretrained model (checkpoint) be released?

### ISSUE THREAD

**Issue by imabackstabber** [OpenGVLab/Vision-RWKV#19]
Hi, I wonder whether the pre-trained model will be released. Any plan or schedule for open-source?

**Comment by duanduanduanyuchen** [comment]
> Hi, I wonder whether the pre-trained model will be released. Any plan or schedule for open-source?

Hi, all models are available. You can click the link in the charts in [model-zoo](https://github.com/OpenGVLab/Vision-RWKV?tab=readme-ov-file#model-zoo), or download them in the [huggingface repo](https://huggingface.co/OpenGVLab/Vision-RWKV/tree/main)

**Comment by duanduanduanyuchen** [comment]
We didn't do the human pose estimation task. You can fine-tune a model using VRWKV as the backbone by [MMPose](https://github.com/open-mmlab/mmpose) if you like.

**Comment by imabackstabber** [comment]
ok, thanks for replying.
