### ISSUE TITLE
能否做一个替代GPT-4vision能力的版本，我们正在做一个商业&公益兼具的产品

### ISSUE THREAD

**Issue by baleli668** [OpenGVLab/Vision-RWKV#2]
大神，你好
我们正在使用GPT-4vision能力做一款商业&公益兼具的产品，但GPT-4vision价格贵、处理速度慢，
是否可以跟你合作，使用vision-RWKV做出能力替代？

期待你的回信，也可以微信联系我：kobe_heizi

感谢

**Comment by BlinkDL** [comment]
@baleli668 你可以看 https://github.com/howard-hou/VisualRWKV

**Comment by baleli668** [comment]
感谢 pengbo， 有部署好可以直接体验效果的吗？



---原始邮件---
发件人: "PENG ***@***.***&gt;
发送时间: 2024年3月4日(周一) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenGVLab/Vision-RWKV] 能否做一个替代GPT-4vision能力的版本，我们正在做一个商业&amp;公益兼具的产品 (Issue #2)




 
@baleli668 你可以看 https://github.com/howard-hou/VisualRWKV

**Comment by BlinkDL** [comment]
@baleli668 在 https://huggingface.co/spaces/BlinkDL/RWKV-Gradio-1 是 Visual RWKV v5 1.5B

**Comment by baleli668** [comment]
bopeng,你好
目前vision-RWKV与gpt-4vision或者通义、阶跃星辰等的图片识别理解差距非常大，暂时无法达到商用状态。











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenGVLab/Vision-RWKV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenGVLab/Vision-RWKV] 能否做一个替代GPT-4vision能力的版本，我们正在做一个商业&amp;公益兼具的产品 (Issue #2)





 
@baleli668 你可以看 https://github.com/howard-hou/VisualRWKV
