### ISSUE TITLE
MAE pretraining

### ISSUE THREAD

**Issue by sahilqure** [OpenGVLab/Vision-RWKV#22]
It will be really nice if you could provide us the code for MAE pretraining.

**Comment by duanduanduanyuchen** [comment]
> It will be really nice if you could provide us the code for MAE pretraining.

Hi, we follow the code of [facebookresearch/mae](https://github.com/facebookresearch/mae) for MAE pertaining. The token shift is changed to a 1D direction in the model.

**Comment by INGg** [comment]
I also want pretrained code, it would be even better if it could be made public

**Comment by duanduanduanyuchen** [comment]
Hi, the mae code is uploaded. Please refer to this link: [mae code](https://github.com/OpenGVLab/Vision-RWKV/tree/master/classification/mae).
