### ISSUE TITLE
May I ask if the VRWKV6 will function properly if the depth in VRWKV6 is changed to 1?

### ISSUE THREAD

**Issue by Lixuanhe** [OpenGVLab/Vision-RWKV#27]
Dear Author,

Hello! May I ask if the VRWKV6 will function properly if the depth in VRWKV6 is changed to 1?

**Comment by duanduanduanyuchen** [comment]
> Dear Author,
> 
> Hello! May I ask if the VRWKV6 will function properly if the depth in VRWKV6 is changed to 1?

The initial value may have some problems here. You can use zero/xavier init. This will affect the performance slightly.

**Comment by Lixuanhe** [comment]
How long have you been training? I'm using a 4090, and training 1 epoch with VRWKV6 is particularly slow.
