### ISSUE TITLE
您好，想学习下您的工作，能问能否提供下运行环境中各个库的版本

### ISSUE THREAD

**Issue by Castrol68** [OpenGVLab/Vision-RWKV#3]
您好，想学习下您的工作，能问能否提供下运行环境中各个库的版本

**Comment by duanduanduanyuchen** [comment]
感谢您的关注，我的运行环境主要的版本包括：
```
Python: 3.10.9
CUDA: 11.3
GCC: 7.5.0
```
以及一些主要python库的版本为：
```
torch: 1.12.1+cu113
torchaudio: 0.12.1+cu113
torchvision: 0.13.1+cu113
timm: 0.6.12
mmcv-full: 1.7.0
mmcls: 0.25.0
mmdet: 2.28.2
mmsegmentation: 0.30.0
```
更多的细节您可以参考各个文件夹里的README文件：[classification](https://github.com/OpenGVLab/Vision-RWKV/blob/master/classification/README.md), [detection](https://github.com/OpenGVLab/Vision-RWKV/blob/master/detection/README.md), [segmentation](https://github.com/OpenGVLab/Vision-RWKV/blob/master/segmentation/README.md)
