### ISSUE TITLE
可视化代码

### ISSUE THREAD

**Issue by goodnight111111111** [OpenGVLab/Vision-RWKV#36]
感谢您的论文，注意力图是怎么可视化的，能否分享您的代码

**Comment by Yaziwel** [comment]
> 感谢您的论文，注意力图是怎么可视化的，能否分享您的代码

是ERF吗？这里有一份代码[https://github.com/Yaziwel/Restore-RWKV/blob/main/erf_visualization.py](https://github.com/Yaziwel/Restore-RWKV/blob/main/erf_visualization.py)

**Comment by goodnight111111111** [comment]
> > 感谢您的论文，注意力图是怎么可视化的，能否分享您的代码
> 
> 是ERF吗？这里有一份代码 https://github.com/Yaziwel/Restore-RWKV/blob/main/erf_visualization.py

非常感谢！非常感谢！
