### ISSUE TITLE
关于MAE预训练的问题

### ISSUE THREAD

**Issue by INGg** [OpenGVLab/Vision-RWKV#42]
作者您好，我想问一下关于使用MAE预训练而将Q-Shift操作改为双向是否是因为在mask之后，失去了原有的四方向相邻关系从而无法进行Q-shift操作吗？从而转向以mask后的patch在B L N的L维度上的相邻进行前后的双向Shift吗？

期待您的回复。

**Comment by duanduanduanyuchen** [comment]
是这样的，可以用双向或者单向的shift替代q-shift，在后续finetune的时候再切换回来。
