### ISSUE TITLE
About the T_MAX parameter

### ISSUE THREAD

**Issue by stefenmax** [OpenGVLab/Vision-RWKV#8]
Hi, thanks for your work. I want to train this model in my own dataset in npy format. The image size is 256*256*3. But the T is  calculated to 16384 which that means I need to set a huge T_MAX number. Can you tell me why this happen? Thanks

**Comment by BlinkDL** [comment]
Hi it's related to the backward in RWKV cuda.

This can be solved with better code to achieve infctx (and const speed), stay tuned.
